// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1073.EncoderTest.subsystems;

import org.usfirst.frc1073.EncoderTest.RobotMap;
import org.usfirst.frc1073.EncoderTest.commands.*;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveTrain extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController frontLeftJag = RobotMap.driveTrainfrontLeftJag;
    SpeedController frontRightJag = RobotMap.driveTrainfrontRightJag;
    SpeedController backLeftJag = RobotMap.driveTrainbackLeftJag;
    SpeedController backRightJag = RobotMap.driveTrainbackRightJag;
    RobotDrive mecanumDrive = RobotMap.driveTrainmecanumDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    float speed = 0;
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new Drive());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    public void move(float x, float y, float twist){
    	mecanumDrive.mecanumDrive_Cartesian(x, y, twist, 0);
    }
    
    public void move(){
    	frontLeftJag.set(-speed);
    	frontRightJag.set(speed);
    	backLeftJag.set(-speed);
    	backRightJag.set(speed);
    }
    public void stop(){
    	frontLeftJag.set(0);
    	frontRightJag.set(0);
    	backRightJag.set(0);
    	backLeftJag.set(0);
    }
    public void increaseSpeed(){
    	speed += 0.05;
    }
    public void decreaseSpeed(){
    	speed -= 0.05;
    }
    public float getSpeed(){
    	return speed;
    }
    public void stopSpeed(){
    	speed = 0;
    }
    public void setSpeed(float setSpeed){
    	speed = setSpeed;
    }
    public void moveFrontRight(){
    	frontRightJag.set(speed);
    }
}

